
version: 0.2
env:
  secrets-manager:
    AWS_ACCESS_KEY_ID: "devopskeys:AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "devopskeys:AWS_SECRET_ACCESS_KEY"
    AWS_DEFAULT_REGION: "devopskeys:AWS_DEFAULT_REGION"

phases:
 
  pre_build:
    commands:
      - ls
      - cd "$CODEBUILD_SRC_DIR"
      - echo $Name
      - echo $secretskeys
      - echo $AWS_ACCESS_KEY_ID
      

  build:
    commands:
      -  aws sts get-caller-identity 
      - ls -lrt   
      - terraform init 
      - terraform plan  
      #- export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      #-  export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      #-  export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - aws sts get-caller-identity
      #- mkdir ~/.aws
      #- echo "[devops]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials
      #- echo "[profile devops]\nregion=$AWS_DEFAULT_REGION\noutput=json" > ~/.aws/config
      #- aws sts get-caller-identity
      #- aws sts get-caller-identity --profile devops
      #- aws s3 ls --profile devops
      - aws s3 ls
  post_build:
    commands:
      - echo terraform plan completed on `date`
