
version: 0.2

phases:
 
  pre_build:
    commands:
      - ls
      - cd "$CODEBUILD_SRC_DIR"
      - echo $Name
      - echo $secretskeys
      

  build:
    commands:
      - ls -lrt   
      - terraform init 
      - terraform plan  

  post_build:
    commands:
      - echo terraform plan completed on `date`
